patients = [
    {'id': 101, 'nom': 'Moulin', 'gravite': 3, 'symptomes': 'Entorse de la cheville'},
    {'id': 102, 'nom': 'Adam', 'gravite': 3, 'symptomes': 'Migraine avec nausées'},
    {'id': 103, 'nom': 'Guillot', 'gravite': 3, 'symptomes': 'Crise de panique'},
    {'id': 104, 'nom': 'Durand', 'gravite': 4, 'symptomes': 'Fièvre légère'},
    {'id': 105, 'nom': 'Marchand', 'gravite': 4, 'symptomes': 'Éruption cutanée bénigne'},
    {'id': 106, 'nom': 'Lefèvre', 'gravite': 0, 'symptomes': 'AVC avec hémiplégie'},
    {'id': 107, 'nom': 'Dupont', 'gravite': 1, 'symptomes': 'Douleur thoracique intense'},
    {'id': 108, 'nom': 'Leroy', 'gravite': 2, 'symptomes': 'Fracture du poignet'},
    {'id': 109, 'nom': 'Moreau', 'gravite': 4, 'symptomes': 'Toux sèche'},
    {'id': 110, 'nom': 'Martin', 'gravite': 0, 'symptomes': 'Arrêt cardiaque'},
    {'id': 111, 'nom': 'Rousseau', 'gravite': 1, 'symptomes': 'Brûlure au deuxième degré'},
    {'id': 112, 'nom': 'Blanc', 'gravite': 2, 'symptomes': 'Douleur abdominale aiguë'},
    {'id': 113, 'nom': 'Girard', 'gravite': 3, 'symptomes': 'Infection respiratoire'},
    {'id': 114, 'nom': 'Bernard', 'gravite': 4, 'symptomes': 'Hoquet persistant'},
    {'id': 115, 'nom': 'Petit', 'gravite': 1, 'symptomes': 'Crise d’épilepsie'},
    {'id': 116, 'nom': 'Robert', 'gravite': 1, 'symptomes': 'Infarctus du myocarde'},
    {'id': 117, 'nom': 'Richard', 'gravite': 2, 'symptomes': 'Luxation de l’épaule'},
    {'id': 118, 'nom': 'Dubois', 'gravite': 3, 'symptomes': 'Douleur lombaire'},
    {'id': 119, 'nom': 'Leroy', 'gravite': 4, 'symptomes': 'Douleur dentaire légère'},
    {'id': 120, 'nom': 'Durand', 'gravite': 0, 'symptomes': 'Hémorragie interne'},
    {'id': 121, 'nom': 'Fontaine', 'gravite': 4, 'symptomes': 'Éruption cutanée bénigne'},
    {'id': 122, 'nom': 'Monnier', 'gravite': 0, 'symptomes': 'Perte de connaissance brève'},
    {'id': 123, 'nom': 'Chevalier', 'gravite': 1, 'symptomes': 'Embolie pulmonaire'},
    {'id': 124, 'nom': 'Robin', 'gravite': 2, 'symptomes': 'Hypertension artérielle maligne'},
    {'id': 125, 'nom': 'Clement', 'gravite': 3, 'symptomes': 'Brûlure d’estomac'},
    {'id': 126, 'nom': 'Dufour', 'gravite': 4, 'symptomes': 'Fièvre légère'},
    {'id': 127, 'nom': 'Brun', 'gravite': 0, 'symptomes': 'Arrêt cardiaque'},
    {'id': 128, 'nom': 'Gallois', 'gravite': 1, 'symptomes': 'Crise d’asthme sévère'},
    {'id': 129, 'nom': 'Paris', 'gravite': 2, 'symptomes': 'Infection urinaire compliquée'},
    {'id': 130, 'nom': 'Maurice', 'gravite': 3, 'symptomes': 'Crise de panique'},
    {'id': 131, 'nom': 'Bouchet', 'gravite': 4, 'symptomes': 'Coupure superficielle (doigt)'},
    {'id': 132, 'nom': 'Cousin', 'gravite': 0, 'symptomes': 'Crise de tachychardie'},
    {'id': 133, 'nom': 'Germain', 'gravite': 1, 'symptomes': 'Fracture ouverte du bras'},
    {'id': 134, 'nom': 'Renard', 'gravite': 2, 'symptomes': 'Crise d’angoisse sévère'},
    {'id': 135, 'nom': 'Leclerc', 'gravite': 3, 'symptomes': 'Migraine avec nausées'},
    {'id': 136, 'nom': 'Payet', 'gravite': 4, 'symptomes': 'Toux sèche'},
    {'id': 137, 'nom': 'Rolland', 'gravite': 0, 'symptomes': 'AVC avec hémiplégie'},
    {'id': 138, 'nom': 'Lecomte', 'gravite': 1, 'symptomes': 'Douleur thoracique intense'},
    {'id': 139, 'nom': 'Herve', 'gravite': 4, 'symptomes': 'Hoquet persistant'},
    {'id': 140, 'nom': 'Barbier', 'gravite': 0, 'symptomes': 'Hémorragie interne'},
    {'id': 141, 'nom': 'Dubois', 'gravite': 1, 'symptomes': 'Brûlure au deuxième degré'},
    {'id': 142, 'nom': 'Collet', 'gravite': 2, 'symptomes': 'Douleur abdominale aiguë'},
    {'id': 143, 'nom': 'Menard', 'gravite': 3, 'symptomes': 'Infection respiratoire'},
    {'id': 144, 'nom': 'Boyer', 'gravite': 4, 'symptomes': 'Douleur dentaire légère'},
    {'id': 145, 'nom': 'Boulanger', 'gravite': 0, 'symptomes': 'Crise d’épilepsie'},
    {'id': 146, 'nom': 'Lemaire', 'gravite': 1, 'symptomes': 'Infarctus du myocarde'},
    {'id': 147, 'nom': 'Bourgeois', 'gravite': 2, 'symptomes': 'Luxation de l’épaule'},
    {'id': 148, 'nom': 'Pierre', 'gravite': 3, 'symptomes': 'Douleur lombaire'},
    {'id': 149, 'nom': 'Jacquet', 'gravite': 4, 'symptomes': 'Éruption cutanée bénigne'},
    {'id': 150, 'nom': 'Benard', 'gravite': 0, 'symptomes': 'Perte de connaissance brève'},
    {'id': 151, 'nom': 'Leroux', 'gravite': 1, 'symptomes': 'Embolie pulmonaire'},
    {'id': 152, 'nom': 'Marchal', 'gravite': 2, 'symptomes': 'Hypertension artérielle maligne'},
    {'id': 153, 'nom': 'Weber', 'gravite': 3, 'symptomes': 'Brûlure d’estomac'},
    {'id': 154, 'nom': 'Mallet', 'gravite': 4, 'symptomes': 'Fièvre légère'},
    {'id': 155, 'nom': 'Vasseur', 'gravite': 0, 'symptomes': 'Arrêt cardiaque'},
    {'id': 156, 'nom': 'Perrin', 'gravite': 1, 'symptomes': 'Crise d’asthme sévère'},
    {'id': 157, 'nom': 'Le Roux', 'gravite': 2, 'symptomes': 'Infection urinaire compliquée'},
    {'id': 158, 'nom': 'Guichard', 'gravite': 3, 'symptomes': 'Crise de panique'},
    {'id': 159, 'nom': 'Brun', 'gravite': 4, 'symptomes': 'Coupure superficielle (doigt)'},
    {'id': 160, 'nom': 'Jacobs', 'gravite': 0, 'symptomes': 'AVC avec hémiplégie'},
    {'id': 161, 'nom': 'Coste', 'gravite': 1, 'symptomes': 'Douleur thoracique intense'},
    {'id': 162, 'nom': 'Guillot', 'gravite': 2, 'symptomes': 'Fracture du poignet'},
    {'id': 163, 'nom': 'Toussaint', 'gravite': 3, 'symptomes': 'Migraine avec nausées'},
    {'id': 164, 'nom': 'Colas', 'gravite': 4, 'symptomes': 'Toux sèche'},
    {'id': 165, 'nom': 'Meyer', 'gravite': 0, 'symptomes': 'Crise de tachychardie'},
    {'id': 166, 'nom': 'Da Silva', 'gravite': 1, 'symptomes': 'Brûlure au deuxième degré'},
    {'id': 167, 'nom': 'Charrier', 'gravite': 2, 'symptomes': 'Douleur abdominale aiguë'},
    {'id': 168, 'nom': 'Pires', 'gravite': 3, 'symptomes': 'Infection respiratoire'},
    {'id': 169, 'nom': 'Renault', 'gravite': 4, 'symptomes': 'Hoquet persistant'},
    {'id': 170, 'nom': 'Klein', 'gravite': 0, 'symptomes': 'Hémorragie interne'},
    {'id': 171, 'nom': 'Adam', 'gravite': 1, 'symptomes': 'Infarctus du myocarde'},
    {'id': 172, 'nom': 'Faivre', 'gravite': 2, 'symptomes': 'Luxation de l’épaule'},
    {'id': 173, 'nom': 'Arnaud', 'gravite': 3, 'symptomes': 'Douleur lombaire'},
    {'id': 174, 'nom': 'Roy', 'gravite': 4, 'symptomes': 'Douleur dentaire légère'},
    {'id': 175, 'nom': 'Caron', 'gravite': 0, 'symptomes': 'Crise d’épilepsie'},
    {'id': 176, 'nom': 'Gilbert', 'gravite': 1, 'symptomes': 'Embolie pulmonaire'},
    {'id': 177, 'nom': 'Barbe', 'gravite': 2, 'symptomes': 'Hypertension artérielle maligne'},
    {'id': 178, 'nom': 'Dupuis', 'gravite': 3, 'symptomes': 'Brûlure d’estomac'},
    {'id': 179, 'nom': 'Vidal', 'gravite': 4, 'symptomes': 'Fièvre légère'},
    {'id': 180, 'nom': 'Brunet', 'gravite': 0, 'symptomes': 'Perte de connaissance brève'},
    {'id': 181, 'nom': 'Renard', 'gravite': 1, 'symptomes': 'Crise d’asthme sévère'},
    {'id': 182, 'nom': 'Marin', 'gravite': 2, 'symptomes': 'Infection urinaire compliquée'},
    {'id': 183, 'nom': 'Hebert', 'gravite': 3, 'symptomes': 'Crise de panique'},
    {'id': 184, 'nom': 'Sanchez', 'gravite': 4, 'symptomes': 'Coupure superficielle (doigt)'},
    {'id': 185, 'nom': 'Laporte', 'gravite': 0, 'symptomes': 'Arrêt cardiaque'},
    {'id': 186, 'nom': 'Delannoy', 'gravite': 1, 'symptomes': 'Douleur thoracique intense'},
    {'id': 187, 'nom': 'Leger', 'gravite': 2, 'symptomes': 'Fracture du poignet'},
    {'id': 188, 'nom': 'Bailly', 'gravite': 3, 'symptomes': 'Migraine avec nausées'},
    {'id': 189, 'nom': 'Besson', 'gravite': 4, 'symptomes': 'Toux sèche'},
    {'id': 190, 'nom': 'Charpentier', 'gravite': 0, 'symptomes': 'AVC avec hémiplégie'},
    {'id': 191, 'nom': 'Delaunay', 'gravite': 1, 'symptomes': 'Brûlure au deuxième degré'},
    {'id': 192, 'nom': 'Millet', 'gravite': 2, 'symptomes': 'Douleur abdominale aiguë'},
    {'id': 193, 'nom': 'Pottier', 'gravite': 3, 'symptomes': 'Infection respiratoire'},
    {'id': 194, 'nom': 'Leblanc', 'gravite': 4, 'symptomes': 'Hoquet persistant'},
    {'id': 195, 'nom': 'Buisson', 'gravite': 0, 'symptomes': 'Hémorragie interne'},
    {'id': 196, 'nom': 'Sauvage', 'gravite': 1, 'symptomes': 'Infarctus du myocarde'},
    {'id': 197, 'nom': 'Moulin', 'gravite': 2, 'symptomes': 'Luxation de l’épaule'},
    {'id': 198, 'nom': 'Bouvier', 'gravite': 3, 'symptomes': 'Douleur lombaire'},
    {'id': 199, 'nom': 'Tremblay', 'gravite': 4, 'symptomes': 'Douleur dentaire légère'},
    {'id': 200, 'nom': 'Mathieu', 'gravite': 0, 'symptomes': 'Crise de tachychardie'},
    {'id': 201, 'nom': 'Dupuy', 'gravite': 2, 'symptomes': 'Luxation de l’épaule'},
    {'id': 202, 'nom': 'Fernandez', 'gravite': 3, 'symptomes': 'Brûlure d’estomac'},
    {'id': 203, 'nom': 'Morel', 'gravite': 4, 'symptomes': 'Fièvre légère'},
    {'id': 204, 'nom': 'Simon', 'gravite': 0, 'symptomes': 'Arrêt cardiaque'},
    {'id': 205, 'nom': 'Marchand', 'gravite': 1, 'symptomes': 'Crise d’asthme sévère'},
    {'id': 206, 'nom': 'Aubry', 'gravite': 2, 'symptomes': 'Infection urinaire compliquée'},
    {'id': 207, 'nom': 'Schmitt', 'gravite': 3, 'symptomes': 'Crise de panique'},
    {'id': 208, 'nom': 'Marty', 'gravite': 4, 'symptomes': 'Coupure superficielle (doigt)'},
    {'id': 209, 'nom': 'Joly', 'gravite': 0, 'symptomes': 'AVC avec hémiplégie'},
    {'id': 210, 'nom': 'Carre', 'gravite': 1, 'symptomes': 'Douleur thoracique intense'},
    {'id': 211, 'nom': 'Aubert', 'gravite': 2, 'symptomes': 'Fracture du poignet'},
    {'id': 212, 'nom': 'Leconte', 'gravite': 3, 'symptomes': 'Migraine avec nausées'},
    {'id': 213, 'nom': 'Herve', 'gravite': 4, 'symptomes': 'Toux sèche'},
    {'id': 214, 'nom': 'Barbier', 'gravite': 0, 'symptomes': 'Crise d’épilepsie'},
    {'id': 215, 'nom': 'Dubois', 'gravite': 1, 'symptomes': 'Embolie pulmonaire'},
    {'id': 216, 'nom': 'Collet', 'gravite': 2, 'symptomes': 'Hypertension artérielle maligne'},
    {'id': 217, 'nom': 'Menard', 'gravite': 3, 'symptomes': 'Brûlure d’estomac'},
    {'id': 218, 'nom': 'Boyer', 'gravite': 4, 'symptomes': 'Fièvre légère'},
    {'id': 219, 'nom': 'Boulanger', 'gravite': 0, 'symptomes': 'Perte de connaissance brève'},
    {'id': 220, 'nom': 'Lemaire', 'gravite': 1, 'symptomes': 'Infarctus du myocarde'},
    {'id': 221, 'nom': 'Pottier', 'gravite': 4, 'symptomes': 'Fièvre légère'},
    {'id': 222, 'nom': 'Leblanc', 'gravite': 0, 'symptomes': 'Arrêt cardiaque'},
    {'id': 223, 'nom': 'Buisson', 'gravite': 1, 'symptomes': 'Crise d’asthme sévère'},
    {'id': 224, 'nom': 'Sauvage', 'gravite': 2, 'symptomes': 'Infection urinaire compliquée'},
    {'id': 225, 'nom': 'Moulin', 'gravite': 3, 'symptomes': 'Crise de panique'},
    {'id': 226, 'nom': 'Bouvier', 'gravite': 4, 'symptomes': 'Coupure superficielle (doigt)'},
    {'id': 227, 'nom': 'Tremblay', 'gravite': 0, 'symptomes': 'Hémorragie interne'},
    {'id': 228, 'nom': 'Mathieu', 'gravite': 1, 'symptomes': 'Brûlure au deuxième degré'},
    {'id': 229, 'nom': 'Lelievre', 'gravite': 2, 'symptomes': 'Douleur abdominale aiguë'},
    {'id': 230, 'nom': 'Cordier', 'gravite': 3, 'symptomes': 'Infection respiratoire'},
    {'id': 231, 'nom': 'Gillet', 'gravite': 4, 'symptomes': 'Hoquet persistant'},
    {'id': 232, 'nom': 'Mallet', 'gravite': 1, 'symptomes': 'Crise de tachychardie'},
    {'id': 233, 'nom': 'Perrin', 'gravite': 1, 'symptomes': 'Douleur thoracique intense'},
    {'id': 234, 'nom': 'Le Roux', 'gravite': 2, 'symptomes': 'Fracture du poignet'},
    {'id': 235, 'nom': 'Guichard', 'gravite': 3, 'symptomes': 'Migraine avec nausées'},
    {'id': 236, 'nom': 'Jacobs', 'gravite': 4, 'symptomes': 'Toux sèche'},
    {'id': 237, 'nom': 'Coste', 'gravite': 0, 'symptomes': 'AVC avec hémiplégie'},
    {'id': 238, 'nom': 'Guillot', 'gravite': 1, 'symptomes': 'Embolie pulmonaire'},
    {'id': 239, 'nom': 'Toussaint', 'gravite': 2, 'symptomes': 'Hypertension artérielle maligne'},
    {'id': 240, 'nom': 'Colas', 'gravite': 3, 'symptomes': 'Brûlure d’estomac'},
    {'id': 241, 'nom': 'Blanc', 'gravite': 0, 'symptomes': 'Crise d’épilepsie'},
    {'id': 242, 'nom': 'Meyer', 'gravite': 1, 'symptomes': 'Infarctus du myocarde'},
    {'id': 243, 'nom': 'Da Silva', 'gravite': 2, 'symptomes': 'Luxation de l’épaule'},
    {'id': 244, 'nom': 'Charrier', 'gravite': 3, 'symptomes': 'Douleur lombaire'},
    {'id': 245, 'nom': 'Pires', 'gravite': 4, 'symptomes': 'Douleur dentaire légère'},
    {'id': 246, 'nom': 'Renault', 'gravite': 0, 'symptomes': 'Perte de connaissance brève'},
    {'id': 247, 'nom': 'Klein', 'gravite': 1, 'symptomes': 'Crise d’asthme sévère'},
    {'id': 248, 'nom': 'Adam', 'gravite': 2, 'symptomes': 'Infection urinaire compliquée'},
    {'id': 249, 'nom': 'Faivre', 'gravite': 3, 'symptomes': 'Crise de panique'},
    {'id': 250, 'nom': 'Arnaud', 'gravite': 4, 'symptomes': 'Éruption cutanée bénigne'},
    {'id': 251, 'nom': 'Roy', 'gravite': 0, 'symptomes': 'Arrêt cardiaque'},
    {'id': 252, 'nom': 'Caron', 'gravite': 1, 'symptomes': 'Brûlure au deuxième degré'},
    {'id': 253, 'nom': 'Gilbert', 'gravite': 2, 'symptomes': 'Douleur abdominale aiguë'},
    {'id': 254, 'nom': 'Barbe', 'gravite': 3, 'symptomes': 'Infection respiratoire'},
    {'id': 255, 'nom': 'Dupuis', 'gravite': 4, 'symptomes': 'Fièvre légère'},
    {'id': 256, 'nom': 'Vidal', 'gravite': 0, 'symptomes': 'Hémorragie interne'},
    {'id': 257, 'nom': 'Brunet', 'gravite': 1, 'symptomes': 'Infarctus du myocarde'},
    {'id': 258, 'nom': 'Marin', 'gravite': 2, 'symptomes': 'Luxation de l’épaule'},
    {'id': 259, 'nom': 'Hebert', 'gravite': 3, 'symptomes': 'Douleur lombaire'},
    {'id': 260, 'nom': 'Sanchez', 'gravite': 4, 'symptomes': 'Coupure superficielle (doigt)'},
    {'id': 261, 'nom': 'Sauvage', 'gravite': 3, 'symptomes': 'Migraine avec nausées'},
    {'id': 262, 'nom': 'Laporte', 'gravite': 4, 'symptomes': 'Toux sèche'},
    {'id': 263, 'nom': 'Delannoy', 'gravite': 0, 'symptomes': 'AVC avec hémiplégie'},
    {'id': 264, 'nom': 'Leger', 'gravite': 1, 'symptomes': 'Douleur thoracique intense'},
    {'id': 265, 'nom': 'Bailly', 'gravite': 2, 'symptomes': 'Fracture du poignet'},
    {'id': 266, 'nom': 'Besson', 'gravite': 3, 'symptomes': 'Brûlure d’estomac'},
    {'id': 267, 'nom': 'Charpentier', 'gravite': 4, 'symptomes': 'Hoquet persistant'},
    {'id': 268, 'nom': 'Delaunay', 'gravite': 2, 'symptomes': 'Crise de tachychardie'},
    {'id': 269, 'nom': 'Millet', 'gravite': 1, 'symptomes': 'Embolie pulmonaire'},
    {'id': 270, 'nom': 'Pottier', 'gravite': 2, 'symptomes': 'Hypertension artérielle maligne'},
    {'id': 271, 'nom': 'Leblanc', 'gravite': 3, 'symptomes': 'Infection respiratoire'},
    {'id': 272, 'nom': 'Buisson', 'gravite': 4, 'symptomes': 'Fièvre légère'},
    {'id': 273, 'nom': 'Sauvage', 'gravite': 0, 'symptomes': 'Arrêt cardiaque'},
    {'id': 274, 'nom': 'Moulin', 'gravite': 1, 'symptomes': 'Crise d’asthme sévère'},
    {'id': 275, 'nom': 'Bouvier', 'gravite': 2, 'symptomes': 'Infection urinaire compliquée'},
    {'id': 276, 'nom': 'Tremblay', 'gravite': 3, 'symptomes': 'Crise de panique'},
    {'id': 277, 'nom': 'Mathieu', 'gravite': 4, 'symptomes': 'Coupure superficielle (doigt)'},
    {'id': 278, 'nom': 'Lelievre', 'gravite': 0, 'symptomes': 'Hémorragie interne'},
    {'id': 279, 'nom': 'Cordier', 'gravite': 1, 'symptomes': 'Infarctus du myocarde'},
    {'id': 280, 'nom': 'Gillet', 'gravite': 2, 'symptomes': 'Luxation de l’épaule'},
    {'id': 281, 'nom': 'Guerin', 'gravite': 1, 'symptomes': 'Brûlure au deuxième degré'},
    {'id': 282, 'nom': 'Mallet', 'gravite': 2, 'symptomes': 'Douleur abdominale aiguë'},
    {'id': 283, 'nom': 'Perrin', 'gravite': 3, 'symptomes': 'Douleur lombaire'},
    {'id': 284, 'nom': 'Le Roux', 'gravite': 4, 'symptomes': 'Douleur dentaire légère'},
    {'id': 285, 'nom': 'Guichard', 'gravite': 1, 'symptomes': 'Perte de connaissance brève'},
    {'id': 286, 'nom': 'Jacobs', 'gravite': 1, 'symptomes': 'Embolie pulmonaire'},
    {'id': 287, 'nom': 'Coste', 'gravite': 2, 'symptomes': 'Hypertension artérielle maligne'},
    {'id': 288, 'nom': 'Guillot', 'gravite': 3, 'symptomes': 'Brûlure d’estomac'},
    {'id': 289, 'nom': 'Toussaint', 'gravite': 4, 'symptomes': 'Fièvre légère'},
    {'id': 290, 'nom': 'Colas', 'gravite': 0, 'symptomes': 'Arrêt cardiaque'},
    {'id': 291, 'nom': 'Meyer', 'gravite': 1, 'symptomes': 'Crise d’asthme sévère'},
    {'id': 292, 'nom': 'Da Silva', 'gravite': 2, 'symptomes': 'Infection urinaire compliquée'},
    {'id': 293, 'nom': 'Charrier', 'gravite': 3, 'symptomes': 'Crise de panique'},
    {'id': 294, 'nom': 'Pires', 'gravite': 4, 'symptomes': 'Toux sèche'},
    {'id': 295, 'nom': 'Renault', 'gravite': 0, 'symptomes': 'AVC avec hémiplégie'},
    {'id': 296, 'nom': 'Klein', 'gravite': 1, 'symptomes': 'Douleur thoracique intense'},
    {'id': 297, 'nom': 'Adam', 'gravite': 2, 'symptomes': 'Fracture du poignet'},
    {'id': 298, 'nom': 'Faivre', 'gravite': 3, 'symptomes': 'Migraine avec nausées'},
    {'id': 299, 'nom': 'Arnaud', 'gravite': 4, 'symptomes': 'Éruption cutanée bénigne'},
    {'id': 300, 'nom': 'Joly', 'gravite': 1, 'symptomes': 'Douleur thoracique intense'}
]
